// Regenerates the stats tables in PROGRESS.md between the STATS and LESSONS markers.
import fs from "node:fs";
import path from "node:path";
import { readAllTracks, readLessons, readRoadmap } from "../src/lib/load";
import { LEVELS } from "../src/lib/schema";

const START = "<!-- STATS:START -->";
const END = "<!-- STATS:END -->";
const file = path.join(process.cwd(), "PROGRESS.md");

const tracks = new Map(readAllTracks().map((t) => [t.id, t]));
const rows: string[] = [
  "| Track | Status | Total | Easy | Med | Hard | Senior | Proj | verify |",
  "|---|---|---:|---:|---:|---:|---:|---:|---:|",
];
let total = 0;
for (const tier of readRoadmap().tiers) {
  for (const id of tier.tracks) {
    const t = tracks.get(id);
    if (!t) {
      rows.push(`| ${id} | missing | 0 | | | | | | |`);
      continue;
    }
    const c = (l: string) => t.questions.filter((q) => q.level === l).length;
    total += t.questions.length;
    const verify = t.questions.filter((q) => q.verify).length;
    rows.push(
      `| ${t.id} ${t.title} | ${t.status} | ${t.questions.length} | ${LEVELS.map(c).join(" | ")} | ${verify || ""} |`,
    );
  }
}
rows.push(`| **Total** | | **${total}** | | | | | | |`);

// --- Lessons ---------------------------------------------------------------------------------
const lessonRows: string[] = [
  "| Track | State | Lessons | Planned | Drafted | Reviewed | Words | Mermaid | Qs linked | verify |",
  "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|",
];
const sum = { lessons: 0, planned: 0, drafted: 0, reviewed: 0, words: 0 };
for (const tier of readRoadmap().tiers) {
  for (const id of tier.tracks) {
    const t = tracks.get(id);
    if (!t) continue;
    const ls = readLessons(id);
    const n = (st: string) => ls.filter((l) => l.status === st).length;
    const [planned, drafted, reviewed] = [n("planned"), n("drafted"), n("reviewed")];
    const words = ls.reduce((w, l) => w + l.words, 0);
    const mermaid = ls.reduce((m, l) => m + (l.body.match(/```mermaid/g) ?? []).length, 0);
    const linked = new Set(ls.flatMap((l) => l.questions)).size;
    const verify = ls.filter((l) => l.verify).length;
    const state = !ls.length
      ? "todo"
      : reviewed === ls.length
        ? "reviewed"
        : planned === 0
          ? "drafted"
          : planned === ls.length
            ? "outlined"
            : "in progress";
    sum.lessons += ls.length;
    sum.planned += planned;
    sum.drafted += drafted;
    sum.reviewed += reviewed;
    sum.words += words;
    lessonRows.push(
      `| ${t.id} | ${state} | ${ls.length} | ${planned || ""} | ${drafted || ""} | ${reviewed || ""} | ${words || ""} | ${mermaid || ""} | ${linked ? `${linked}/${t.questions.length}` : ""} | ${verify || ""} |`,
    );
  }
}
lessonRows.push(
  `| **Total** | | **${sum.lessons}** | ${sum.planned} | ${sum.drafted} | ${sum.reviewed} | ${sum.words} | | | |`,
);

const stamp = `_Generated by \`npm run progress\` on ${new Date().toISOString().slice(0, 10)}._`;
function replaceBlock(md: string, start: string, end: string, body: string) {
  const i = md.indexOf(start);
  const j = md.indexOf(end);
  if (i < 0 || j < 0) throw new Error(`PROGRESS.md is missing the ${start} … ${end} markers`);
  return `${md.slice(0, i + start.length)}\n${stamp}\n\n${body}\n${md.slice(j)}`;
}
let md = fs.readFileSync(file, "utf8");
md = replaceBlock(md, START, END, rows.join("\n"));
md = replaceBlock(md, "<!-- LESSONS:START -->", "<!-- LESSONS:END -->", lessonRows.join("\n"));
fs.writeFileSync(file, md);
console.log(
  `PROGRESS.md updated: ${tracks.size} tracks, ${total} questions, ${sum.lessons} lessons (${sum.drafted + sum.reviewed} written, ${sum.words} words)`,
);
