// Regenerates the stats table in PROGRESS.md between the STATS markers.
import fs from "node:fs";
import path from "node:path";
import { readAllTracks, readRoadmap } from "../src/lib/load";
import { LEVELS } from "../src/lib/schema";

const START = "<!-- STATS:START -->";
const END = "<!-- STATS:END -->";
const file = path.join(process.cwd(), "PROGRESS.md");

const tracks = new Map(readAllTracks().map((t) => [t.id, t]));
const rows: string[] = [
  "| Track | Status | Total | Easy | Med | Hard | Senior | Proj | verify |",
  "|---|---|---:|---:|---:|---:|---:|---:|---:|",
];
let total = 0;
for (const tier of readRoadmap().tiers) {
  for (const id of tier.tracks) {
    const t = tracks.get(id);
    if (!t) {
      rows.push(`| ${id} | missing | 0 | | | | | | |`);
      continue;
    }
    const c = (l: string) => t.questions.filter((q) => q.level === l).length;
    total += t.questions.length;
    const verify = t.questions.filter((q) => q.verify).length;
    rows.push(
      `| ${t.id} ${t.title} | ${t.status} | ${t.questions.length} | ${LEVELS.map(c).join(" | ")} | ${verify || ""} |`,
    );
  }
}
rows.push(`| **Total** | | **${total}** | | | | | | |`);

const md = fs.readFileSync(file, "utf8");
const i = md.indexOf(START);
const j = md.indexOf(END);
if (i < 0 || j < 0) throw new Error("PROGRESS.md is missing the STATS markers");
const stamp = `_Generated by \`npm run progress\` on ${new Date().toISOString().slice(0, 10)}._`;
fs.writeFileSync(file, `${md.slice(0, i + START.length)}\n${stamp}\n\n${rows.join("\n")}\n${md.slice(j)}`);
console.log(`PROGRESS.md updated: ${tracks.size} tracks, ${total} questions`);
